### ISSUE TITLE
Не обновляется баланс изначально пустого кошелька, подключенного через walletConnect

### ISSUE THREAD

**Issue by Leeroooy** [knownout/evm-wallet-controller#5]
Шаги:
1. Подключиться через walletConnect к мобильному кошельку, который ни разу не пополнялся на кор валюту в подключаемой сети
2. Пока кошелек подключен к бриджу, пополнить баланс кор валюты подключенного кошелька

Факт:
Баланс не обновляется в режиме реального времени. В консольных логах присутствует запрос баланса только в момент подключения, но далее баланс не запрашивается каждые 5 сек.

(Additional info: если после подключения подождать около 5-10 минут, а затем переподключиться на экстиншен метамаска, то баланс тоже перестанет опрашиваться, однако при повторном подключении к метамаску, баланс начнет опрашиваться)

Ожидание:
Баланс подключенного евм кошелька должен обновляться в режиме реального времени

**Comment by knownout** [comment]
Должно быть исправлено в версии 0.1.33

**Comment by Leeroooy** [comment]
master refactor stand - ok
