### ISSUE TITLE
Ошибочный статус подключения в ЕВМ модалке при отказе от подключения метамаска/койнбейза/воллетконнекта

### ISSUE THREAD

**Issue by Leeroooy** [knownout/evm-wallet-controller#6]
Шаги:
1. Предварительно отключить соединение с бриджом в экстиншене метамаска/койнбейза/walletconnect
2. На бридже вызвать присоединение к любому из кошельков, но в кошельке зарежектить соединение

Факт:
В модалке будет указано, что бридж подключен к кошельку в случае браузерных экстеншенов. В случае мобильного подключения через WalletConnect модалка QR закроется и будет указано зависшее Connecting...

https://prnt.sc/VcvBv51FCWh5
https://prnt.sc/Bw-uGF2ZsuuL
https://prnt.sc/YyzByOoIFOe9

Ожидание:
при отказе от подключения в кошельке модалка должна возвращаться в исходное состояние (выбор кошелька для подключения)

**Comment by knownout** [comment]
Исправлено в версии 0.1.33

**Comment by Leeroooy** [comment]
refactoring stand - fixed
