### ISSUE TITLE
Автоматически не опрашивается баланс Coinbase после установления первого коннекта

### ISSUE THREAD

**Issue by Leeroooy** [knownout/evm-wallet-controller#7]
Шаги:
1. Прервать соединение с сайтом бриджа в настройках Coinbase (Dapp Connections), в случае если ранее был подключен Coinbase
2. Сбросить все стораджи/кеши/куки
3. Захардрелоадить страницу бриджа
4. Подключить кошелек Coinbase (чтобы вызвалась модалка экстиншена, там нажать Connect)

Факт:
баланс не автообновляется, в консоли отсутствуют опрашивания баланса каждые 5 сек. Если обновить страницу, и затем отключить/подключить койнбейз - баланс уже будет обновляться. (когда уже есть dapp connection с бриджом)

Ожидание:
баланс на фронте должен всегда актуализироваться в реальном времени для подключенного Coinbase

**Comment by knownout** [comment]
Исправлено в версии 0.1.33

**Comment by Leeroooy** [comment]
refactoring stand - fixed
