### ISSUE TITLE
Прерывание walletConnect-соединения из мобилки отключает подключенный экстиншен браузерного метамаска/койнбейза

### ISSUE THREAD

**Issue by Leeroooy** [knownout/evm-wallet-controller#8]
Шаги:
1. С пк версии бриджа подсоединить мобильный кошелек через WalletConnect (моб метамаск/трастволлет/wallet3/etc)
2. Переподключиться на браузерный кошелек через экстиншен метамаска/койнбейза
3. С мобильного кошелька прервать соединение walletconnect с бриджом (в настройках самого моб кошелька в walletconnect connections / dapp connections)

Факт:
Произойдет отсоединение браузерного кошелька 

Ожидание:
т.к. подключен браузерный кошелек, удаленное прерывание соединения walletconnect не должно вызывать отключение браузерного кошелька

**Comment by knownout** [comment]
Исправлено в версии 0.1.33

**Comment by Leeroooy** [comment]
refactoring stand - fixed
