### ISSUE TITLE
Не отслеживается отключение мобильного WalletConnect после перезагрузки страницы

### ISSUE THREAD

**Issue by Leeroooy** [knownout/evm-wallet-controller#9]
Шаги:
1. Подключиться через walletconnect (на трастволлет/моб метамаск/wallet3/etc)
2. Перезагрузить страницу
3. В мобильном кошельке прервать соединение walletconnect

Факт:
евм кошелек не будет визуально отключен на фронте. Если после этого еще раз перезагрузить страницу, то будет вечный лоадер на кнопке подключения евм кошелька до тех пор, пока не перезагрузить страницу еще раз

Ожидание:
бридж должен отслеживать отключение walletconnect текущего подключенного кошелька

**Comment by knownout** [comment]
Исправлено в версии 0.1.33

**Comment by Leeroooy** [comment]
refactoring stand - fixed
